name: "Bigfile Tests"
on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request_target:
    types: [opened]
    branches:
      - 'master'
      - 'release/**'
      - 'releases/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      # only bigfile dependencies are being cached,
      # those are not updated everyday and this is
      # unecessary to fetch them everytime.
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            _build/default/lib/accept
            _build/default/lib/b64fast
            _build/default/lib/cowboy
            _build/default/lib/cowlib
            _build/default/lib/gun
            _build/default/lib/jiffy
            _build/default/lib/prometheus
            _build/default/lib/prometheus_cowboy
            _build/default/lib/prometheus_httpd
            _build/default/lib/prometheus_process_collector
            _build/default/lib/quantile_estimator
            _build/default/lib/ranch
            _build/default/lib/.rebar3
            _build/default/lib/recon
            _build/default/lib/rocksdb
            _build/default/plugins/
            _build/default/plugins/aleppo
            _build/default/plugins/geas
            _build/default/plugins/geas_rebar3
            _build/default/plugins/hex_core
            _build/default/plugins/katana_code
            _build/default/plugins/pc
            _build/default/plugins/.rebar3
            _build/default/plugins/rebar3_archive_plugin
            _build/default/plugins/rebar3_elvis_plugin
            _build/default/plugins/rebar3_hex
            _build/default/plugins/samovar
            _build/default/plugins/verl
            _build/default/plugins/zipper
          key: deps-cache-${{ hashFiles('rebar.lock') }}
          restore-keys: |
            deps-cache-${{ hashFiles('rebar.lock') }}

      - name: Get dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./big-rebar3 test get-deps

      - uses: actions/cache@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: |
            _build/default/lib/accept
            _build/default/lib/b64fast
            _build/default/lib/cowboy
            _build/default/lib/cowlib
            _build/default/lib/gun
            _build/default/lib/jiffy
            _build/default/lib/prometheus
            _build/default/lib/prometheus_cowboy
            _build/default/lib/prometheus_httpd
            _build/default/lib/prometheus_process_collector
            _build/default/lib/quantile_estimator
            _build/default/lib/ranch
            _build/default/lib/.rebar3
            _build/default/lib/recon
            _build/default/lib/rocksdb
            _build/default/plugins/
            _build/default/plugins/aleppo
            _build/default/plugins/geas
            _build/default/plugins/geas_rebar3
            _build/default/plugins/hex_core
            _build/default/plugins/katana_code
            _build/default/plugins/pc
            _build/default/plugins/.rebar3
            _build/default/plugins/rebar3_archive_plugin
            _build/default/plugins/rebar3_elvis_plugin
            _build/default/plugins/rebar3_hex
            _build/default/plugins/samovar
            _build/default/plugins/verl
            _build/default/plugins/zipper
          key: deps-cache-${{ hashFiles('rebar.lock') }}

      - name: Compile arweave release
        run: ./big-rebar3 default release

      - name: Build arweave test sources
        run: ./big-rebar3 test compile

      # some artifacts are compiled and only available
      # in arweave directy (libraries)
      - name: Prepare artifacts
        run: |
          chmod -R u+w ./_build
          tar czfp _build.tar.gz ./_build ./bin/bigfile
          tar czfp apps.tar.gz ./apps

      # to avoid reusing artifacts from someone else
      # and generating issues, an unique artifact is
      # produced using github checksum.
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          path: |
            _build.tar.gz
            apps.tar.gz

      # some artifacts are compiled and only available
      # in arweave directy (libraries)
      - name: Prepare artifacts
        run: |
          chmod -R u+w ./_build
          tar czfp _build.tar.gz ./_build
          tar czfp apps.tar.gz ./apps

      # to avoid reusing artifacts from someone else
      # and generating issues, an unique artifact is
      # produced using github checksum.
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 7
          overwrite: true
          path: |
            _build.tar.gz
            apps.tar.gz

  ####################################################################
  # Canary testing, should fail.
  ####################################################################
  canary:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}

      # Both artifacts (_build and apps dir) are
      # required.
      - name: Extract artifact
        run: |
          tar zxfp _build.tar.gz
          tar zxfp apps.tar.gz

      - id: canary
        name: big_canary.erl
        continue-on-error: true
        run: bash scripts/github_workflow.sh "tests" "big_canary"

      - name: should fail
        run: |
          if test "${{ steps.canary.outcome }}" = "failure"
          then
            exit 0
          else
            exit 1
          fi

  ####################################################################
  # Long-running tests. Put these first to limit the overall runtime
  # of the test suite
  ####################################################################
  eunit-tests-long-running:
    needs: canary
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        core_test_mod: [
            ## Long-running tests. Put these first to limit the overall runtime of the
            ## test suite
            big_coordinated_mining_tests,
            big_data_sync_tests,
            big_fork_recovery_tests,
            big_tx,
            big_packing_tests,
            big_poa,
            big_vdf_server_tests,
            big_post_block_tests,
            big_reject_chunks_tests
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}

      # Both artifacts (_build and apps dir) are
      # required.
      - name: Extract artifact
        run: |
          tar zxfp _build.tar.gz
          tar zxfp apps.tar.gz

      - name: ${{ matrix.core_test_mod }}.erl
        id: tests
        run: bash scripts/github_workflow.sh "tests" "${{ matrix.core_test_mod }}"

      # this part of the job produces test artifacts from logs
      # generated by the tests. It also collect dumps and the files
      # present in .tmp (temporary arweave data store)
      - name: upload artifacts in case of failure
        uses: actions/upload-artifact@v4
        if: always() && failure()
        with:
          name: "logs-${{ matrix.core_test_mod }}-${{ github.run_attempt }}-${{ job.status }}-${{ runner.name }}-${{ github.sha }}"
          retention-days: 7
          overwrite: true
          include-hidden-files: true
          path: |
            ./logs
            *.out
            *.dump

  ####################################################################
  # Modules containing tests
  ####################################################################
  eunit-tests-modules:
    needs: canary
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        core_test_mod: [
            big,
            big_block,
            big_block_cache,
            big_chain_stats,
            big_chunk_copy,
            big_chunk_storage,
            big_data_sync_worker_master,
            big_deep_hash,
            big_device_lock,
            big_diff_dag,
            big_entropy_storage,
            big_ets_intervals,
            big_events,
            big_inflation,
            big_intervals,
            big_join,
            big_kv,
            big_merkle,
            big_mining_server,
            big_mining_stats,
            big_node,
            big_node_utils,
            big_nonce_limiter,
            # big_p3,
            # big_p3_config,
            # big_p3_db,
            big_packing_server,
            big_patricia_tree,
            big_peers,
            big_pricing,
            big_replica_2_9,
            big_retarget,
            big_serialize,
            big_storage_module,
            big_storage,
            big_sync_buckets,
            big_sync_record,
            big_tx_db,
            big_unbalanced_merkle,
            big_util,
            big_verify_chunks,
            big_wallet,
            big_webhook,
            big_pool
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}

      # Both artifacts (_build and apps dir) are
      # required.
      - name: Extract artifact
        run: |
          tar zxfp _build.tar.gz
          tar zxfp apps.tar.gz

      - name: ${{ matrix.core_test_mod }}.erl
        id: tests
        run: bash scripts/github_workflow.sh "tests" "${{ matrix.core_test_mod }}"

      # this part of the job produces test artifacts from logs
      # generated by the tests. It also collect dumps and the files
      # present in .tmp (temporary arweave data store)
      - name: upload artifacts in case of failure
        uses: actions/upload-artifact@v4
        if: always() && failure()
        with:
          name: "logs-${{ matrix.core_test_mod }}-${{ github.run_attempt }}-${{ job.status }}-${{ runner.name }}-${{ github.sha }}"
          retention-days: 7
          overwrite: true
          include-hidden-files: true
          path: |
            ./logs
            *.out
            *.dump

  ####################################################################
  # Test modules (note: that _tests are implicitly run by a matching
  # prefix name
  ####################################################################
  eunit-tests-suite:
    needs: canary
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        core_test_mod: [
            big_base64_compatibility_tests,
            big_config_tests,
            big_difficulty_tests,
            big_header_sync_tests,
            big_http_iface_tests,
            big_http_util_tests,
            big_info_tests,
            big_mempool_tests,
            big_mine_randomx_tests,
            big_mine_vdf_tests,
            big_mining_io_tests,
            big_poller_tests,
            big_reject_chunks_tests,
            big_replica_2_9_nif_tests,
            big_semaphore_tests,
            big_start_from_block_tests,
            big_tx_blacklist_tests,
            big_tx_replay_pool_tests,
            big_vdf_tests,
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}

      # Both artifacts (_build and apps dir) are
      # required.
      - name: Extract artifact
        run: |
          tar zxfp _build.tar.gz
          tar zxfp apps.tar.gz

      - name: ${{ matrix.core_test_mod }}.erl
        id: tests
        run: bash scripts/github_workflow.sh "tests" "${{ matrix.core_test_mod }}"

      # this part of the job produces test artifacts from logs
      # generated by the tests. It also collect dumps and the files
      # present in .tmp (temporary arweave data store)
      - name: upload artifacts in case of failure
        uses: actions/upload-artifact@v4
        if: always() && failure()
        with:
          name: "logs-${{ matrix.core_test_mod }}-${{ github.run_attempt }}-${{ job.status }}-${{ runner.name }}-${{ github.sha }}"
          retention-days: 7
          overwrite: true
          include-hidden-files: true
          path: |
            ./logs
            *.out
            *.dump
